# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markdocify < Formula
  desc "Convert documentation websites into consolidated markdown files"
  homepage "https://github.com/vladkampov/markdocify"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.2/markdocify_0.0.2_darwin_amd64.tar.gz"
      sha256 "8567774e8e6ae3df4a53c6b5542244fb57e5b8e07b249de7522ce5c3ff740a87"

      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.2/markdocify_0.0.2_darwin_arm64.tar.gz"
      sha256 "d4b16c4664be3d7a825c7ca2d79d77a8cb85cd963871feeb9b3b6052caeba7f9"

      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.2/markdocify_0.0.2_linux_amd64.tar.gz"
      sha256 "49ba87046b54a9fecbad15e8c73794fcb4b9579fb15e7d142b7ce8b07d7d6abc"
      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.2/markdocify_0.0.2_linux_arm64.tar.gz"
      sha256 "20ca4e8d1ab3b8a4e5c7572729783bd06be0bf9291708991ffadbef8e16cec4b"
      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/markdocify --version")

    # Test help output
    help_output = shell_output("#{bin}/markdocify --help")
    assert_match "markdocify is a CLI tool", help_output
  end
end
