# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markdocify < Formula
  desc "Convert documentation websites into consolidated markdown files"
  homepage "https://github.com/vladkampov/markdocify"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.3/markdocify_0.0.3_darwin_amd64.tar.gz"
      sha256 "5c5ef51b51f59b7aecfd2e8b47e708b184b8a0ed3537dda800d40e44935e99be"

      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.3/markdocify_0.0.3_darwin_arm64.tar.gz"
      sha256 "8d7d72a22064fb857ad76b66ca9a6dc790adee1e6085dbb2e86e7a69fb1b29b1"

      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.3/markdocify_0.0.3_linux_amd64.tar.gz"
      sha256 "f7c132610adc4dcc4d7a11527b1760f7481c3023da9ea8802abb592db3fcd3da"
      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vladkampov/markdocify/releases/download/v0.0.3/markdocify_0.0.3_linux_arm64.tar.gz"
      sha256 "a2b99c489e16895b1aa0fe0332e477ac3eb77a1488561f301960c18c780d8dff"
      def install
        bin.install "markdocify"

        # Install example configurations
        pkgshare.install "configs" if File.exist?("configs")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/markdocify --version")

    # Test help output
    help_output = shell_output("#{bin}/markdocify --help")
    assert_match "markdocify is a CLI tool", help_output
  end
end
